//
//  UpdateMyStatusUseCaseModel.swift
//  Generated by Clean Architecture Template
//

import Foundation

public struct UpdateMyStatusUseCase: Hashable, Identifiable {
    public let id: UUID
    
    public init(id: UUID) {
        self.id = id
    }
}
