//
//  UpdateMyStatusUseCaseTests.swift
//  Generated by Clean Architecture Template
//

import XCTest
import Foundation
@testable import UFree

final class UpdateMyStatusUseCaseTests: XCTestCase {
    
    func test_init_createsModelWithId() {
        let id = UUID()
        let sut = UpdateMyStatusUseCase(id: id)
        
        XCTAssertEqual(sut.id, id)
    }
    
    func test_equality_comparesById() {
        let id = UUID()
        let sut1 = UpdateMyStatusUseCase(id: id)
        let sut2 = UpdateMyStatusUseCase(id: id)
        
        XCTAssertEqual(sut1, sut2)
    }
}
