//
//  UpdateMyStatusUseCaseUIIntegrationTests.swift
//  Generated by Clean Architecture Template
//

import XCTest
import Combine
@testable import UFree

// MARK: - Helpers

private func makeUpdateMyStatusUseCase() -> UpdateMyStatusUseCase {
    UpdateMyStatusUseCase(id: UUID())
}

@MainActor
final class UpdateMyStatusUseCaseUIIntegrationTests: XCTestCase {
    
    func test_updatemystatususecaseView_hasTitle() {
        let (sut, _) = makeSUT()
        
        XCTAssertEqual(sut.title, UpdateMyStatusUseCasePresenter.title)
    }
    
    // MARK: - Helpers
    
    private func makeSUT(file: StaticString = #filePath, line: UInt = #line) -> (UIViewController, LoaderSpy) {
        let loader = LoaderSpy()
        let sut = UpdateMyStatusUseCaseComposer.LUpdateMyStatusUseCaseComposedWith(loader: loader.loadPublisher)
        trackForMemoryLeaks(sut, file: file, line: line)
        trackForMemoryLeaks(loader, file: file, line: line)
        return (sut, loader)
    }
    
    @MainActor
    private class LoaderSpy {
        private var requests = [PassthroughSubject<UpdateMyStatusUseCase, Error>]()
        
        var loadCallCount: Int {
            return requests.count
        }
        
        func loadPublisher() -> AnyPublisher<UpdateMyStatusUseCase, Error> {
            let publisher = PassthroughSubject<UpdateMyStatusUseCase, Error>()
            requests.append(publisher)
            return publisher.eraseToAnyPublisher()
        }
        
        func completeLoading(with LUpdateMyStatusUseCase: UpdateMyStatusUseCase = makeUpdateMyStatusUseCase(), at index: Int = 0) {
            requests[index].send(LUpdateMyStatusUseCase)
            requests[index].send(completion: .finished)
        }
        
        func completeLoadingWithError(at index: Int = 0) {
            requests[index].send(completion: .failure(anyNSError()))
        }
    }
}
