//
//  UpdateMyStatusUseCaseViewModel.swift
//  Generated by Clean Architecture Template
//

import Foundation

public struct UpdateMyStatusUseCaseViewModel: Identifiable, Hashable {
    public let id: UUID
    
    public init(id: UUID) {
        self.id = id
    }
}
