//
//  UpdateMyStatusUseCasePresenter.swift
//  Generated by Clean Architecture Template
//

import Foundation

public final class UpdateMyStatusUseCasePresenter {
    public static var title: String {
        NSLocalizedString(
            "UPDATEMYSTATUSUSECASE_VIEW_TITLE",
            tableName: "UpdateMyStatusUseCase",
            bundle: Bundle(for: UpdateMyStatusUseCasePresenter.self),
            comment: "Title for the updatemystatususecase view"
        )
    }
    
    public static func map(_ LUpdateMyStatusUseCase: UpdateMyStatusUseCase) -> UpdateMyStatusUseCaseViewModel {
        UpdateMyStatusUseCaseViewModel(id: LUpdateMyStatusUseCase.id)
    }
}
