//
//  UpdateMyStatusUseCasePresenter.swift
//  Generated by Clean Architecture Template
//

import Foundation

public final class UpdateMyStatusUseCasePresenter {
    public static var title: String {
        NSLocalizedString(
            "UPDATEMYSTATUSUSECASE_VIEW_TITLE",
            tableName: "UpdateMyStatusUseCase",
            bundle: Bundle(for: UpdateMyStatusUseCasePresenter.self),
            comment: "Title for the updatemystatususecase view"
        )
    }
    
    // NOTE: This method is deprecated - kept for compatibility with old template code
    // The new implementation uses SwiftUI and MyScheduleViewModel instead
    public static func map(_ LUpdateMyStatusUseCase: UpdateMyStatusUseCase) -> UpdateMyStatusUseCaseViewModel {
        // Return a placeholder view model - this is only used by old template tests
        UpdateMyStatusUseCaseViewModel(id: UUID())
    }
}
