//
//  UpdateMyStatusUseCaseMapper.swift
//  Generated by Clean Architecture Template
//

import Foundation

public enum UpdateMyStatusUseCaseMapper {
    public static func map(_ data: Data, from response: HTTPURLResponse) throws -> UpdateMyStatusUseCase {
        guard response.statusCode == 200 else {
            throw UpdateMyStatusUseCaseMapper.Error.invalidData
        }
        
        // TODO: Implement JSON decoding
        // let json = try JSONDecoder().decode(RemoteUpdateMyStatusUseCase.self, from: data)
        // return json.toModel()
        
        throw UpdateMyStatusUseCaseMapper.Error.notImplemented
    }
    
    enum Error: Swift.Error {
        case invalidData
        case notImplemented
    }
}
