//
//  UpdateMyStatusUseCaseAPI.swift
//  Generated by Clean Architecture Template
//

import Foundation
import Combine

public protocol UpdateMyStatusUseCaseAPI {
    func loadUpdateMyStatusUseCase() -> AnyPublisher<UpdateMyStatusUseCase, Error>
}
