//
//  UpdateMyStatusUseCasePresenterTests.swift
//  Generated by Clean Architecture Template
//

import XCTest
import Foundation
@testable import UpdateMyStatusUseCase

final class UpdateMyStatusUseCasePresenterTests: XCTestCase {
    
    func test_map_createsViewModel() {
        let model = UpdateMyStatusUseCase(id: UUID())
        let viewModel = UpdateMyStatusUseCasePresenter.map(model)
        
        XCTAssertEqual(viewModel.id, model.id)
    }
}
