//
//  LocalUpdateMyStatusUseCaseModel.swift
//  Generated by Clean Architecture Template
//

import Foundation

public struct LocalUpdateMyStatusUseCase: Codable {
    public let id: UUID
    
    public init(id: UUID) {
        self.id = id
    }
}

extension LocalUpdateMyStatusUseCase {
    func toModel() -> UpdateMyStatusUseCase {
        UpdateMyStatusUseCase(id: id)
    }
}

extension UpdateMyStatusUseCase {
    func toLocal() -> LocalUpdateMyStatusUseCase {
        LocalUpdateMyStatusUseCase(id: id)
    }
}
