//
//  LocalUpdateMyStatusUseCaseModel.swift
//  Generated by Clean Architecture Template
//

import Foundation

public struct LocalUpdateMyStatusUseCase: Codable {
    public let id: UUID
    
    public init(id: UUID) {
        self.id = id
    }
}

// NOTE: These extensions are deprecated - UpdateMyStatusUseCase is now a use case class, not a model
// This file is kept for compatibility with old template code but the conversions are no longer valid
// The new implementation uses DayAvailability and AvailabilityRepository directly
