//
//  UpdateMyStatusUseCaseStore.swift
//  Generated by Clean Architecture Template
//

import Foundation

public protocol UpdateMyStatusUseCaseStore {
    func save(_ LUpdateMyStatusUseCase: UpdateMyStatusUseCase) throws
    func load() throws -> UpdateMyStatusUseCase?
    func delete() throws
}
