//
//  UpdateMyStatusUseCaseViewAdapter.swift
//  Generated by Clean Architecture Template (UIKit)
//

import UIKit

@MainActor
final class UpdateMyStatusUseCaseViewAdapter: ResourceView {
    private weak var controller: ListViewController?
    
    init(controller: ListViewController) {
        self.controller = controller
    }
    
    func display(_ viewModel: UpdateMyStatusUseCaseViewModel) {
        // TODO: Implement view model display logic
        // controller?.display([CellController(id: viewModel.id, ...)])
    }
}
