//
//  UpdateMyStatusUseCaseComposer.swift
//  Generated by Clean Architecture Template (UIKit)
//

import UIKit
import Combine

@MainActor
public final class UpdateMyStatusUseCaseComposer {
    private init() {}
    
    private typealias UpdateMyStatusUseCasePresentationAdapter = LoadResourcePresentationAdapter<UpdateMyStatusUseCase, UpdateMyStatusUseCaseViewAdapter>
    
    public static func LUpdateMyStatusUseCaseComposedWith(
        loader: @escaping () -> AnyPublisher<UpdateMyStatusUseCase, Error>
    ) -> ListViewController {
        let presentationAdapter = UpdateMyStatusUseCasePresentationAdapter(loader: loader)
        
        let controller = makeUpdateMyStatusUseCaseViewController(title: UpdateMyStatusUseCasePresenter.title)
        controller.onRefresh = presentationAdapter.loadResource
        
        presentationAdapter.presenter = LoadResourcePresenter(
            resourceView: UpdateMyStatusUseCaseViewAdapter(controller: controller),
            loadingView: WeakRefVirtualProxy(controller),
            errorView: WeakRefVirtualProxy(controller),
            mapper: UpdateMyStatusUseCasePresenter.map)
        
        return controller
    }
    
    private static func makeUpdateMyStatusUseCaseViewController(title: String) -> ListViewController {
        let controller = ListViewController()
        controller.title = title
        return controller
    }
}
