//
//  UpdateMyStatusUseCaseLoader.swift
//  Generated by Clean Architecture Template
//

import Foundation
import Combine

public protocol UpdateMyStatusUseCaseLoader {
    func load() -> AnyPublisher<UpdateMyStatusUseCase, Error>
}
